#include <com/sun/star/uno/XInterface.idl>

module com_hatenablog_arachansan {

    interface XGetRest : com::sun::star::uno::XInterface
        {
            /** swaps the content of the incoming array */
            string GetRest( [in] string str );
        };
};
